add_newline     = true
command_timeout = 200
format          = "[$directory$git_branch$git_status]($style)$character"
palette = 'theme'

[palettes.theme]
theme_color = '#d4bd99'

[character]
error_symbol    = "[✗](bold theme_color)"
success_symbol  = "[❯](bold theme_color)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style             = "theme_color"
repo_root_style   = "bold theme_color"
repo_root_format  = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format  = "[$branch]($style) "
style   = "italic theme_color"

[git_status]
format     = '[$all_status]($style)'
style      = "theme_color"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
