accent = "#706e6b"
cursor = "#f0e4c5"
foreground = "#f0e4c5"
background = "#32302f"
selection_foreground = "#f0e4c5"
selection_background = "#706e6b"

color0 = "#32302f"
color1 = "#cc241d"
color2 = "#a89984"
color3 = "#ebdbb2"
color4 = "#706e6b"
color5 = "#afa499"
color6 = "#d4bd99"
color7 = "#fbf1c7"
color8 = "#7b6d60"
color9 = "#fb4934"
color10 = "#b8bb26"
color11 = "#fabd2f"
color12 = "#83a598"
color13 = "#d3869b"
color14 = "#8ec07c"
color15 = "#f0e4c5"
