services:
  windows:
    image: dockurr/windows
    container_name: omarchy-windows
    environment:
      VERSION: "11"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "64G"
      USERNAME: "docker"
      PASSWORD: "0nlyg00dwind0wsisvm"
      ARGUMENTS: "-device usb-host,vendorid=0x0951,productid=0x1665" # Kingston Data Traveler
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/kr9sis/.windows:/storage
      - /home/kr9sis/Windows:/shared
    restart: on-failure
    stop_grace_period: 2m
